version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    environment:
      - APP_ENV=dev

  webserver:
    image: nginx:alpine
    container_name: symfony_webserver
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
